### ISSUE TITLE
translate json en_US to es_ES 

### ISSUE THREAD

**Issue by heroelocopro** [Rushbycmd/DR-Translations#1]
[es_ES.json.json](https://github.com/user-attachments/files/16327417/es_ES.json.json)

hello, i want to help in the translate

**Comment by Ditatury** [comment]
I don't know if they've already translated it on Github into PT-BR, but here it is. I hope this small contribution helps you, good luck with the game's development, I'm rooting for you and your group!

[pt_BR.json](https://github.com/user-attachments/files/16336122/pt_BR.json)

**Comment by Rushbycmd** [comment]
Hey, copy the en_US and just translate the second part of each field in the strings and errors.

**Comment by heroelocopro** [comment]
Hello @Rushbycmd , the file es_ES is already in spanish, tell me if you see any error in the display o hud. 
[es_ES.json (1).json](https://github.com/user-attachments/files/16337875/es_ES.json.1.json)

have a good day.

**Comment by Rushbycmd** [comment]
Have a good day, thanks for helping out!
