### ISSUE TITLE
en_US to pt_BR

### ISSUE THREAD

**Issue by Ditatury** [Rushbycmd/DR-Translations#2]
I don't know if they've already translated it on Github into PT-BR, but here it is. I hope this small contribution helps you, good luck with the game's development, I'm rooting for you and your group!

[pt_BR.json](https://github.com/user-attachments/files/16336408/pt_BR.json)

**Comment by Rushbycmd** [comment]
Hey ditatury, I have received your dms previously, I will need to check everything before finalizing a translation. 
Thanks for your contributions and the kind words <3
